title: Jira Backup Python
description: A Python-based tool for backing up Jira and Confluence to multiple cloud storage providers
remote_theme: just-the-docs/just-the-docs@v0.8.2

url: https://yourusername.github.io # Update with your GitHub username
baseurl: /jira-backup-py

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "Jira Backup Python on GitHub":
    - "//github.com/yourusername/jira-backup-py"

# Makes Aux links open in a new tab
aux_links_new_tab: false

# Sort order for navigation links
nav_sort: case_sensitive

# Footer content
footer_content: "Copyright &copy; 2024 Jira Backup Python. Distributed by an <a href=\"https://github.com/yourusername/jira-backup-py/blob/master/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/yourusername/jira-backup-py"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "tree"

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Google Analytics Tracking (optional)
# ga_tracking: UA-XXXXXXXXX-X
# ga_tracking_anonymize_ip: true

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false